Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision :shell, path: "vagrant/bootstrap.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end  
  config.vm.synced_folder ".", "/home/vagrant/homework7"
  config.vm.network "private_network", type: "dhcp"
end
